namespace Prism.Mvvm
{
    [bindable]
    [default_interface]
    unsealed runtimeclass BindableBase : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		BindableBase();
		protected void RaisePropertyChanged(String propertyName);
	}
}
